# Generated by Django 5.1.2 on 2024-10-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrucciones', models.CharField(max_length=100)),
                ('Porciones', models.CharField(max_length=100)),
                ('tiempo_coccion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Proveedor', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Ingrediente', models.DateTimeField(auto_now_add=True)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Receta', models.CharField(max_length=100)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('Preparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preparacion')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredientes')),
                ('Recetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recetas')),
            ],
        ),
    ]
