# Generated by Django 5.1.2 on 2024-10-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='Nombre_Ingrediente',
            field=models.CharField(max_length=100),
        ),
    ]
